# Configuration Cloudflare Worker - ZIFLIX Streaming Proxy
name = "ziflix-proxy"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGIN = "https://ziablo.xyz"
LOG_LEVEL = "info"

# Secrets requis (injectés de manière sécurisée via wrangler secret put) :
# - XTREAM_HOST (ex: foxbleu.org)
# - XTREAM_PORT (ex: 80)
# - XTREAM_USER (ex: josealbino)
# - XTREAM_PASS (ex: 21321)
# - ADMIN_TOKEN (ex: jeton cryptographique aléatoire)

[[kv_namespaces]]
binding = "CATALOG_KV"
id = "92f6da25e1d7408fa5d666ae8fccf453"
preview_id = "8eec76f36dbe455385a29bfbac8db3ab"

[[kv_namespaces]]
binding = "SERIES_CACHE"
id = "a9ae6e8c6a574b2cb197eb9122fb3391"
preview_id = "9c2fc6bb85b6417baf0efa2a945ea80f"
