const fs = require('fs');
const path = require('path');

const catalog = {
  categories: [
    { id: "c_trends", name: "Tendances actuelles", slug: "tendances" },
    { id: "c_originals", name: "Netflix Originals", slug: "originals" },
    { id: "c_top_rated", name: "Les plus gros succès critiques", slug: "top_rated" },
    { id: "c_action", name: "Films d'action & Blockbusters", slug: "action" },
    { id: "c_series", name: "Séries dramatiques & Thrillers", slug: "series" },
    { id: "c_scifi", name: "Sci-Fi & Mondes fantastiques", slug: "scifi" },
    { id: "c_anime", name: "Animation & Anime", slug: "anime" },
    { id: "c_comedy", name: "Comédies populaires", slug: "comedy" },
    { id: "c_horror", name: "Horreur & Frissons", slug: "horror" },
    { id: "c_docu", name: "Documentaires captivants", slug: "docu" }
  ],
  movies: [
    // --- TENDANCES / ORIGINALS ---
    {
      id: "stranger-things",
      title: "Stranger Things",
      original_title: "Stranger Things",
      overview: "À Hawkins en 1983, la disparition mystérieuse d'un jeune garçon lève le voile sur une série d'expériences gouvernementales top secrètes, des forces surnaturelles et une fillette aux pouvoirs télékinésiques.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      video_url: "https://www.youtube.com/embed/b9EkMc79ZSU?autoplay=1",
      categories: ["Tendances actuelles", "Netflix Originals", "Sci-Fi & Mondes fantastiques"],
      release_year: 2025,
      match_score: 99,
      age_rating: "16+",
      duration: "4 Saisons",
      cast: ["Millie Bobby Brown", "David Harbour", "Winona Ryder", "Finn Wolfhard"],
      director: "Les Frères Duffer",
      quality_badges: ["4K Ultra HD", "Dolby Vision", "Dolby Atmos"],
      is_hero: true,
      created_at: new Date().toISOString()
    },
    {
      id: "squid-game",
      title: "Squid Game",
      original_title: "Squid Game",
      overview: "456 personnes criblées de dettes acceptent de participer à une série de jeux pour enfants mortels dans l'espoir de remporter 45,6 milliards de wons. Mais chaque élimination est fatale.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/dDlGgwXjB19p0p2aK275ZJ2GgqV.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/y4a02U0qQc0q66UaX06Qo2t4q4F.jpg",
      video_url: "https://www.youtube.com/embed/oqxAJKy0ii4?autoplay=1",
      categories: ["Tendances actuelles", "Netflix Originals", "Séries dramatiques & Thrillers"],
      release_year: 2024,
      match_score: 98,
      age_rating: "18+",
      duration: "2 Saisons",
      cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon"],
      director: "Hwang Dong-hyuk",
      quality_badges: ["4K Ultra HD", "HDR", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "mercredi",
      title: "Mercredi",
      original_title: "Wednesday",
      overview: "Tout en apprenant à apprivoiser ses pouvoirs psychiques naissants, Mercredi Addams tente d'élucider un mystère surnaturel vieux de 25 ans qui implique ses parents à la Nevermore Academy.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxKuXAGzrGKiVGKT1n.jpg",
      video_url: "https://www.youtube.com/embed/Di310WS8zLk?autoplay=1",
      categories: ["Tendances actuelles", "Netflix Originals", "Sci-Fi & Mondes fantastiques"],
      release_year: 2024,
      match_score: 97,
      age_rating: "12+",
      duration: "2 Saisons",
      cast: ["Jenna Ortega", "Gwendoline Christie", "Emma Myers"],
      director: "Tim Burton",
      quality_badges: ["4K Ultra HD", "Spatial Audio"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "one-piece-live",
      title: "One Piece",
      original_title: "One Piece",
      overview: "Accompagné de son fidèle chapeau de paille et de son équipage hétéroclite, le jeune pirate Monkey D. Luffy parcourt les mers à la recherche du trésor ultime pour devenir le Roi des Pirates.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuFGxJn595H94q.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/2rmK7mnchsl935x72PmyvxBlCmS.jpg",
      video_url: "https://www.youtube.com/embed/Ades3pQbeh8?autoplay=1",
      categories: ["Tendances actuelles", "Netflix Originals", "Films d'action & Blockbusters"],
      release_year: 2023,
      match_score: 96,
      age_rating: "12+",
      duration: "1 Saison",
      cast: ["Iñaki Godoy", "Mackenyu", "Emily Rudd", "Jacob Romero Gibson"],
      director: "Matt Owens",
      quality_badges: ["4K Ultra HD", "Dolby Atmos"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "lupin",
      title: "Lupin",
      original_title: "Lupin: Dans l'ombre d'Arsène",
      overview: "Inspiré par les aventures d'Arsène Lupin, le gentleman cambrioleur Assane Diop décide de venger son père victime d'une injustice orchestrée par une riche famille.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/sgxawbFB5Vi5OkPWQLNqw3PWhSZ.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/mZjZgYACi2asllYz1RBFumJwSR3.jpg",
      video_url: "https://www.youtube.com/embed/ga0iTWkCGa0?autoplay=1",
      categories: ["Tendances actuelles", "Netflix Originals", "Séries dramatiques & Thrillers"],
      release_year: 2023,
      match_score: 95,
      age_rating: "12+",
      duration: "3 Parties",
      cast: ["Omar Sy", "Ludivine Sagnier", "Clotilde Hesme"],
      director: "Louis Leterrier",
      quality_badges: ["HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- ACTIONS & BLOCKBUSTERS ---
    {
      id: "inception",
      title: "Inception",
      original_title: "Inception",
      overview: "Dom Cobb est un voleur chevronné capable de s'emparer des secrets les plus intimes logés dans le subconscient d'une cible pendant son sommeil. Une ultime mission lui offre une chance de rédemption.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
      video_url: "https://www.youtube.com/embed/YoHD9XEInc0?autoplay=1",
      categories: ["Films d'action & Blockbusters", "Sci-Fi & Mondes fantastiques", "Les plus gros succès critiques"],
      release_year: 2010,
      match_score: 98,
      age_rating: "12+",
      duration: "2h 28m",
      cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
      director: "Christopher Nolan",
      quality_badges: ["4K Ultra HD", "Spatial Audio"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "top-gun-maverick",
      title: "Top Gun: Maverick",
      original_title: "Top Gun: Maverick",
      overview: "Après plus de trente ans de service comme aviateur d'élite de la Navy, Pete 'Maverick' Mitchell entraîne une promotion de diplômés de Top Gun pour une mission spéciale à haut risque.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
      video_url: "https://www.youtube.com/embed/giXco2jaZ_4?autoplay=1",
      categories: ["Films d'action & Blockbusters", "Tendances actuelles"],
      release_year: 2022,
      match_score: 97,
      age_rating: "Tous publics",
      duration: "2h 10m",
      cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
      director: "Joseph Kosinski",
      quality_badges: ["4K Ultra HD", "Dolby Atmos"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "dune-2",
      title: "Dune: Deuxième Partie",
      original_title: "Dune: Part Two",
      overview: "Paul Atreides s'unit à Chani et aux Fremen tout en menant une guerre de vengeance contre les conspirateurs qui ont détruit sa famille. Devant un dilemme fatal, il doit prévenir un sombre futur.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/czembW0Rk1Ke7lCJGzyAiIYID2W.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520DRq.jpg",
      video_url: "https://www.youtube.com/embed/Way9Dexny3w?autoplay=1",
      categories: ["Films d'action & Blockbusters", "Sci-Fi & Mondes fantastiques", "Les plus gros succès critiques"],
      release_year: 2024,
      match_score: 99,
      age_rating: "12+",
      duration: "2h 46m",
      cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
      director: "Denis Villeneuve",
      quality_badges: ["4K Ultra HD", "IMAX Enhanced", "Dolby Atmos"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "tyler-rake-2",
      title: "Tyler Rake 2",
      original_title: "Extraction II",
      overview: "Après avoir survécu de justesse aux événements du premier film, le mercenaire australien des opérations clandestines Tyler Rake se voit confier une nouvelle mission à haut risque : sauver la famille d'un gangster impitoyable.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/7gKI9hpEMcZUwYeCuVmACQC9YHg.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2f89.jpg",
      video_url: "https://www.youtube.com/embed/Y274jqufZPE?autoplay=1",
      categories: ["Films d'action & Blockbusters", "Netflix Originals"],
      release_year: 2023,
      match_score: 94,
      age_rating: "18+",
      duration: "2h 03m",
      cast: ["Chris Hemsworth", "Golshifteh Farahani", "Tornike Gogrichiani"],
      director: "Sam Hargrave",
      quality_badges: ["4K Ultra HD", "Dolby Vision"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "the-dark-knight",
      title: "The Dark Knight: Le Chevalier Noir",
      original_title: "The Dark Knight",
      overview: "Avec l'aide du lieutenant Jim Gordon et du procureur Harvey Dent, Batman s'efforce de démanteler les organisations criminelles de Gotham City. Mais un génie du chaos connu sous le nom du Joker sème la terreur.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
      video_url: "https://www.youtube.com/embed/EXeTwQWrcwY?autoplay=1",
      categories: ["Films d'action & Blockbusters", "Les plus gros succès critiques"],
      release_year: 2008,
      match_score: 99,
      age_rating: "12+",
      duration: "2h 32m",
      cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
      director: "Christopher Nolan",
      quality_badges: ["4K Ultra HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- SCI-FI & FANTASTIQUE ---
    {
      id: "interstellar",
      title: "Interstellar",
      original_title: "Interstellar",
      overview: "Face à une crise écologique majeure menaçant l'humanité de famine, une équipe d'astronautes s'aventure au-delà des confins de la galaxie via un trou de ver afin de trouver une nouvelle planète habitable.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/rAiYTsqJJR0dHw9yQy2Zg4K0Q2F.jpg",
      video_url: "https://www.youtube.com/embed/zSWdZVtXT7E?autoplay=1",
      categories: ["Sci-Fi & Mondes fantastiques", "Les plus gros succès critiques", "Tendances actuelles"],
      release_year: 2014,
      match_score: 99,
      age_rating: "Tous publics",
      duration: "2h 49m",
      cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
      director: "Christopher Nolan",
      quality_badges: ["4K Ultra HD", "Dolby Atmos", "IMAX"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "the-witcher",
      title: "The Witcher",
      original_title: "The Witcher",
      overview: "Geralt de Riv, un chasseur de monstres mutant solitaire, lutte pour trouver sa place dans un monde où les hommes se révèlent souvent plus cruels que les bêtes sauvages.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22swhQ9RB3Gv.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
      video_url: "https://www.youtube.com/embed/ndl1W4ltcmg?autoplay=1",
      categories: ["Sci-Fi & Mondes fantastiques", "Netflix Originals"],
      release_year: 2023,
      match_score: 93,
      age_rating: "18+",
      duration: "3 Saisons",
      cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
      director: "Lauren Schmidt Hissrich",
      quality_badges: ["4K Ultra HD", "HDR"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "3-body-problem",
      title: "Le Problème à 3 corps",
      original_title: "3 Body Problem",
      overview: "Une décision prise en Chine dans les années 60 résonne à travers l'espace et le temps jusqu'à nos jours, poussant un groupe de scientifiques brillants à faire face à la plus grande menace pour l'humanité.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/ykZ0Jv1zS5u1Y2S5zY9Y8w8K0Z0.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/9fYxpqD4x0b8sQ8h6W7uVv2y3Wk.jpg",
      video_url: "https://www.youtube.com/embed/mogSbMD6EcY?autoplay=1",
      categories: ["Sci-Fi & Mondes fantastiques", "Netflix Originals", "Tendances actuelles"],
      release_year: 2024,
      match_score: 96,
      age_rating: "16+",
      duration: "1 Saison",
      cast: ["Benedict Wong", "Jess Hong", "Jovan Adepo", "Eiza González"],
      director: "David Benioff & D.B. Weiss",
      quality_badges: ["4K Ultra HD", "Dolby Vision"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- ANIMATION & ANIME ---
    {
      id: "arcane",
      title: "Arcane",
      original_title: "Arcane: League of Legends",
      overview: "Au cœur du conflit entre l'utopique Piltover et la sombre cité souterraine de Zaun, deux sœurs se retrouvent dans des camps opposés au cours d'une guerre technologique et magique déchirante.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn396FQEGvZY4.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/8h1r62F7Yx0v7w62sJ8mYk5j7s2.jpg",
      video_url: "https://www.youtube.com/embed/fXmAurh012s?autoplay=1",
      categories: ["Animation & Anime", "Sci-Fi & Mondes fantastiques", "Netflix Originals", "Les plus gros succès critiques"],
      release_year: 2024,
      match_score: 99,
      age_rating: "16+",
      duration: "2 Saisons",
      cast: ["Hailee Steinfeld", "Ella Purnell", "Katie Leung"],
      director: "Fortiche Production",
      quality_badges: ["4K Ultra HD", "Dolby Atmos"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "cyberpunk-edgerunners",
      title: "Cyberpunk: Edgerunners",
      original_title: "Cyberpunk: Edgerunners",
      overview: "Dans une mégalopole corrompue et obsédée par la technologie corporelle, David Martinez, un gamin de la rue sans avenir, devient un mercenaire hors-la-loi high-tech pour survivre.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/7jsw9e5unwUioLh1i1q1n2K2nQ9.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/m9P8iA1R8nQ2y1v1m0g9l8l3h0o.jpg",
      video_url: "https://www.youtube.com/embed/JtqIas3bYhg?autoplay=1",
      categories: ["Animation & Anime", "Sci-Fi & Mondes fantastiques", "Netflix Originals"],
      release_year: 2022,
      match_score: 97,
      age_rating: "18+",
      duration: "1 Saison",
      cast: ["KENN", "Aoi Yuuki", "Hiroki Touchi"],
      director: "Studio Trigger",
      quality_badges: ["HDR", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "demon-slayer",
      title: "Demon Slayer: Kimetsu no Yaiba",
      original_title: "Kimetsu no Yaiba",
      overview: "Le jeune Tanjiro Kamado devient pourfendeur de démons après le massacre de sa famille et la transformation de sa sœur Nezuko en démon, déterminé à lui rendre sa forme humaine.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/nTvM4mhqZlHIvUkI1gVnWumQU4Q.jpg",
      video_url: "https://www.youtube.com/embed/VQGCKyvzIM4?autoplay=1",
      categories: ["Animation & Anime", "Tendances actuelles"],
      release_year: 2024,
      match_score: 98,
      age_rating: "16+",
      duration: "4 Saisons",
      cast: ["Natsuki Hanae", "Akari Kito", "Hiro Shimono"],
      director: "Haruo Sotozaki (ufotable)",
      quality_badges: ["HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "spider-verse",
      title: "Spider-Man: Across the Spider-Verse",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview: "Miles Morales est catapulté à travers le multivers, où il rencontre une équipe de Spider-Héros chargée de protéger son existence même, avant de devoir redéfinir ce que signifie être un héros.",
      media_type: "movie",
      poster_url: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      video_url: "https://www.youtube.com/embed/cqGjhVJWtEg?autoplay=1",
      categories: ["Animation & Anime", "Films d'action & Blockbusters", "Les plus gros succès critiques"],
      release_year: 2023,
      match_score: 99,
      age_rating: "Tous publics",
      duration: "2h 20m",
      cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
      director: "Joaquim Dos Santos & Kemp Powers",
      quality_badges: ["4K Ultra HD", "Dolby Atmos"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- SÉRIES DRAMATIQUES & THRILLERS ---
    {
      id: "breaking-bad",
      title: "Breaking Bad",
      original_title: "Breaking Bad",
      overview: "Atteint d'un cancer du poumon en phase terminale, Walter White, professeur de chimie modeste, s'associe à l'un de ses anciens élèves pour fabriquer et vendre de la méthamphétamine.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
      video_url: "https://www.youtube.com/embed/HhesaQXLuRY?autoplay=1",
      categories: ["Séries dramatiques & Thrillers", "Les plus gros succès critiques"],
      release_year: 2013,
      match_score: 99,
      age_rating: "18+",
      duration: "5 Saisons",
      cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Giancarlo Esposito"],
      director: "Vince Gilligan",
      quality_badges: ["4K Ultra HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "peaky-blinders",
      title: "Peaky Blinders",
      original_title: "Peaky Blinders",
      overview: "En 1919 à Birmingham, le redoutable gang des Peaky Blinders, mené par le charismatique et impitoyable Tommy Shelby, bâtit un empire criminel au sortir de la Première Guerre mondiale.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/70NxPdGZp5K8p6K9X7x7x5R3J5.jpg",
      video_url: "https://www.youtube.com/embed/oVzVdvGIC7U?autoplay=1",
      categories: ["Séries dramatiques & Thrillers", "Tendances actuelles"],
      release_year: 2022,
      match_score: 98,
      age_rating: "18+",
      duration: "6 Saisons",
      cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory", "Tom Hardy"],
      director: "Steven Knight",
      quality_badges: ["HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "la-casa-de-papel",
      title: "La Casa de Papel",
      original_title: "Money Heist",
      overview: "Huit voleurs menés par un mystérieux cerveau appelé le Professeur réalisent la plus audacieuse prise d'otages de l'histoire dans la Fabrique nationale de la monnaie d'Espagne.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbk5r6rgAGHG24UW.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/gFZri2YbFUBulAcPNGIRTeiqkqn.jpg",
      video_url: "https://www.youtube.com/embed/hMANIarjT50?autoplay=1",
      categories: ["Séries dramatiques & Thrillers", "Netflix Originals"],
      release_year: 2021,
      match_score: 96,
      age_rating: "16+",
      duration: "5 Parties",
      cast: ["Álvaro Morte", "Úrsula Corberó", "Pedro Alonso"],
      director: "Álex Pina",
      quality_badges: ["HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- COMÉDIES & FEEL GOOD ---
    {
      id: "brooklyn-nine-nine",
      title: "Brooklyn Nine-Nine",
      original_title: "Brooklyn Nine-Nine",
      overview: "Jake Peralta, détective brillant mais immature du 99e commissariat de Brooklyn, voit son quotidien bousculé par l'arrivée du très strict et impassible capitaine Raymond Holt.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/hgRMSOt7a1b8qyQR68vU152LOnW.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/ncC3Z1NuwwZzWz4T3fXkP8b1M6P.jpg",
      video_url: "https://www.youtube.com/embed/sEOuJ4z5aTc?autoplay=1",
      categories: ["Comédies populaires", "Tendances actuelles"],
      release_year: 2021,
      match_score: 97,
      age_rating: "12+",
      duration: "8 Saisons",
      cast: ["Andy Samberg", "Andre Braugher", "Melissa Fumero", "Terry Crews"],
      director: "Dan Goor & Michael Schur",
      quality_badges: ["HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    },
    {
      id: "friends",
      title: "Friends",
      original_title: "Friends",
      overview: "Les joies, les peines et les tribulations amoureuses de six amis new-yorkais inséparables partageant leurs vies entre leurs appartements de Manhattan et le Central Perk.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPghkkxP969Y2.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/l0qVZIpXtIo7km9u5YAV0ecJFI.jpg",
      video_url: "https://www.youtube.com/embed/IEEbUzffzrk?autoplay=1",
      categories: ["Comédies populaires", "Les plus gros succès critiques"],
      release_year: 2004,
      match_score: 98,
      age_rating: "Tous publics",
      duration: "10 Saisons",
      cast: ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matt LeBlanc", "Matthew Perry", "David Schwimmer"],
      director: "David Crane & Marta Kauffman",
      quality_badges: ["HD", "Stereo"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- HORREUR & SUSPENSE ---
    {
      id: "the-haunting-of-hill-house",
      title: "The Haunting of Hill House",
      original_title: "The Haunting of Hill House",
      overview: "Cinq frères et sœurs ayant grandi dans la maison hantée la plus célèbre d'Amérique sont réunis à l'âge adulte par une tragédie familiale qui réveille de terrifiants fantômes du passé.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/3Zs9K7J0G2p4l2B1cW6bT8s9V0a.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/b9mZ5Hq1B3v7R9K1b5bT8s9V0a.jpg",
      video_url: "https://www.youtube.com/embed/G9OzG53VwIk?autoplay=1",
      categories: ["Horreur & Frissons", "Netflix Originals", "Les plus gros succès critiques"],
      release_year: 2018,
      match_score: 96,
      age_rating: "18+",
      duration: "1 Saison",
      cast: ["Michiel Huisman", "Carla Gugino", "Victoria Pedretti"],
      director: "Mike Flanagan",
      quality_badges: ["4K Ultra HD", "HDR"],
      is_hero: false,
      created_at: new Date().toISOString()
    },

    // --- DOCUMENTAIRES CAPTIVANTS ---
    {
      id: "drive-to-survive",
      title: "Formula 1: Pilotes de leur destin",
      original_title: "Formula 1: Drive to Survive",
      overview: "Pilotes, directeurs d'écurie et propriétaires vivent sous haute tension pendant une saison de Formule 1 sans merci où la moindre milliseconde fait la différence.",
      media_type: "series",
      poster_url: "https://image.tmdb.org/t/p/w500/wP5iQ8j1d7K1b5bT8s9V0a1b2c.jpg",
      backdrop_url: "https://image.tmdb.org/t/p/original/m9P8iA1R8nQ2y1v1m0g9l8l3h0o.jpg",
      video_url: "https://www.youtube.com/embed/a4n_Z4UuUj4?autoplay=1",
      categories: ["Documentaires captivants", "Netflix Originals", "Tendances actuelles"],
      release_year: 2024,
      match_score: 96,
      age_rating: "12+",
      duration: "6 Saisons",
      cast: ["Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Toto Wolff"],
      director: "James Gay-Rees",
      quality_badges: ["4K Ultra HD", "5.1"],
      is_hero: false,
      created_at: new Date().toISOString()
    }
  ]
};

const dataDir = path.join(__dirname, '..', 'data');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

fs.writeFileSync(path.join(dataDir, 'catalog.json'), JSON.stringify(catalog, null, 2), 'utf8');
console.log(`[SUCCÈS] Catalogue TMDb généré avec ${catalog.movies.length} titres et ${catalog.categories.length} catégories.`);
